import {
    Container,
    Badge,
    List,
    ListItem,
    Link,
  } from '@chakra-ui/react'
  
  import { Title, WorkImage, Meta } from '../../components/work'
  import P from '../../components/paragraph'
  import Layout from "../../components/layouts/article"
import { ExternalLinkIcon } from '@chakra-ui/icons'



  
const Work = () => {
    return (
        <Layout title="Space Invaderz">
            <Container>
                <Title>
                Space Invaderz<Badge>2022</Badge>
                </Title>
                <P>
                Space Invaders is a game I developed with vanilla HTML and JavaScript.  The main area is made of HTML canvas and the ship is an image using key inputs to move it around. The invaders are in a similar function, but move in grids. Most of the particles from the ship and the invaders are generated by intervals, or in the player's case it is generated by space bar inputs. From this project, I wanted to learn more about HTML canvas and develop my first game. I also designed a ‘How to play’ document, which I made in InDesign and Illustrator. 
                </P>
                <List ml={4} my={4}>

        
                    <Meta>Stack</Meta>
                    <span>Javascript, HTML canvas, InDesign, Illustator</span>

                    <ListItem>
                    <Meta>Role</Meta>
                    <span>Developer & Designer</span>
                    </ListItem>

                    <ListItem>
                    <Meta>Demo</Meta>
                    <Link href='https://space-invaderz-by-zahir.vercel.app/'>
                    https://space-invaderz-by-zahir.vercel.app/ <ExternalLinkIcon mx="2px"/>
                    </Link>
                    </ListItem>

                    <ListItem>
                    <Meta>Github Repo</Meta>
                    <Link href='https://github.com/ZahirA1i/Space_Invader'>
                    https://github.com/ZahirA1i/Space_Invader <ExternalLinkIcon mx="2px"/>
                    </Link>
                    </ListItem>


                </List>

                

                <WorkImage src="/images/contents/SpaceInvader/Space Invaders.png" alt="1"/>
                <WorkImage src="/images/contents/SpaceInvader/Space Invaders2.png" alt="2"/>
                <WorkImage src="/images/contents/SpaceInvader/Space Invaders3.png" alt="3"/>
                <WorkImage src="/images/contents/SpaceInvader/Space Invaders4.png" alt="4"/>
                <WorkImage src="/images/contents/SpaceInvader/Space Invaders5.png" alt="5"/>

                

            </Container>
        </Layout>
    )
}

export default Work